---
version: '3'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  mongo-express:
    # Web-based MongoDB admin interface, written with Node.js and express | https://hub.docker.com/_/mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root     # MongoDB admin username
      ME_CONFIG_MONGODB_ADMINPASSWORD: example  # MongoDB admin password
    depends_on:
      - mongo

  #orderapi-server:
  #  build: './order/order.api'
  #  restart: always
  #  ports:
  #    - 5000:80
  #  environment:
  #    # The environment variable will override the localhost that we have in our appsettings.json file and will allow the service to connect to the mongo server
  #    MongoDB__Host: mongo
  #  depends_on:
  #     - mongo

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
#    network_mode: host
#    hostname: zookeeper
#    ports:
#      - "2181:2181"   
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
#      ZOOKEEPER_SASL_ENABLED: 'FALSE'
    extra_hosts:
      - "moby:127.0.0.1"      
#      - "default:127.0.0.1"            

  kafka:
    # An important note about accessing Kafka from clients on other machines: 
    # The config used here exposes port 9092 for _external_ connections to the broker i.e. those from _outside_ the docker network.
    # This could be from the host machine running docker, or maybe further afield if you've got a more complicated setup. 
    # If the latter is true, you will need to change the value 'localhost' in KAFKA_ADVERTISED_LISTENERS to one that is resolvable 
    # to the docker host from those remote clients
    # For connections _internal_ to the docker network, such as from other services and components, use kafka:29092.
    # See https://rmoff.net/2018/08/02/kafka-listeners-explained/ for details
    # kafka tool: http://www.kafkatool.com/download.html
    image: confluentinc/cp-kafka:latest
#    hostname: kafka
#    network_mode: host
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_ADVERTISED_HOST_NAME: kafka
#      KAFKA_ADVERTISED_PORT: "9092"
    extra_hosts:
      - "moby:127.0.0.1"      
#      - "default:127.0.0.1"             